version: '3'
services:
  auth:
    image: node:12.18.4
    container_name: test_auth_server
    ports:
      - 5001:5001
    working_dir: /code
    environment: 
        - DB_NAME=habitdb
        - DB_USER=root
        - DB_PASS=habitpass
        - DB_URL=mongodb://root:habitpass@db:27017
        - DB_COLLECTION=usercollection
        - PORT=5001
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./auth
        target: /code
    command: bash -c "npm install && npm test"
    tty: true
  db: 
    image: mongo:latest
    container_name: test_auth_db
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./auth/test/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_DATABASE=habitdb
      - MONGO_INITDB_ROOT_PASSWORD=habitpass
volumes:
  dbdata: