version: '3'
services:

    client:
        container_name: habit_client_1
        build: ./client
        image: habit-client
        ports:
          - 8080:8080
        working_dir: /code
        volumes:
          - type: bind
            source: ./client
            target: /code
        command: ["http-server"]
