version: '3'
services:
  api: 
    image: node:12.18.4
    working_dir: /code
    ports:
      - 3000:3000
    environment:
      - DB_NAME=habittracker
      - DB_CONNECTION=mongodb+srv://habit-smashers21:pWGX766l3sYusCMA@habittracker.hms0s.mongodb.net/habitsmasher-db?retryWrites=true&w=majority
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm start"

  auth:
    image: node:12.18.4
    ports: 
      - 5000:5000
    working_dir: /code
    environment: 
      - DB_NAME=habittracker
      - DB_CONNECTION=mongodb+srv://habit-smashers21:pWGX766l3sYusCMA@habittracker.hms0s.mongodb.net/habitsmasher-db?retryWrites=true&w=majority
    volumes:
      - type: bind
        source: ./auth
        target: /code
    command: bash -c "npm install && npm start"
